name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run Unit Tests
      run: mvn test
      
    - name: Run Code Style Check
      run: mvn verify
      
    - name: Deploy Application
      # Add your deployment steps here
      # Example: use SSH, FTP, or cloud platform services for deployment
      
    - name: Certify Candidate Version
      # Add your certification steps here
      # Example: execute integration tests, performance metrics checks, etc.
